export enum DeviceType {
  BIO_UNIVERSAL = 'BIO_UNIVERSAL',
  PELLET_LEVEL = 'PELLET_LEVEL',
  BIO_UNIVERSAL_GEFEST = 'BIO_UNIVERSAL_GEFEST',
  BIO_UNIVERSAL_OVEN = 'BIO_UNIVERSAL_OVEN',
  SMART_SOCKET = 'SMART_SOCKET',
  AIR_TOUCH = 'AIR_TOUCH',
  BIO_UNIVERSAL_HIDE = 'BIO_UNIVERSAL_HIDE',
  TEHNIX = 'TEHNIX',
  NONE = 'NONE'
}
